View all pots
Anima-Tec/2021_Proyecto_Integrador_Equipo_4 pull request #145
Opened 2021-11-08 22:36 UTC by Katherine-Damires

2021-11-09 01:11 UTC, JhonAires-Anima requested changes

2021-11-09 01:11 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/PotsInNeed/index.jsx
> +  const handlePageClick = (newValue) => {
Deberías cambiar el nombre a changePageHandler, ya que así no es muy descriptivo

2021-11-09 01:11 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/ViewAllPots.module.scss
> +@import "../../assets/styles/colors.module.scss";
comillas dobles

2021-11-09 01:11 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/index.jsx
> +import { useState } from "react";
comillas dobles

2021-11-09 01:11 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/index.jsx
> +  const handleChange = (event, newValue) => {
handleChange me parece poco descriptivo, capaz cambiarlo a algo como `tabChangeHandler` es mejor

2021-11-09 01:11 UTC, JhonAires-Anima commented on frontend/src/pages/Home/index.jsx
>      <div className={classes.container}>
Deberías poner todo lo de acá adentro a un componente, para mantener el código en home más legible para futuras expansiones como agregar otra sección, por ejemplo

2021-11-09 01:13 UTC, JhonAires-Anima requested changes

2021-11-09 01:13 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/AllPots/index.jsx
> +              )}
Todo esto debería estar dentro de un componente

2021-11-09 01:20 UTC, Katherine-Damires commented on frontend/src/pages/Home/index.jsx
>      <div className={classes.container}>
tenez razon pero en ver-ollas ya esta hecho quedo solo el titulo, la descripcion y la imagen

2021-11-09 01:28 UTC, Katherine-Damires commented on frontend/src/components/ViewAllPots/AllPots/index.jsx
> +              )}
no puedo por que utiliza la funcion que esta en ese componente para con los pot.

2021-11-09 01:34 UTC, Katherine-Damires commented on frontend/src/components/ViewAllPots/index.jsx
> +import { useState } from "react";
no se por que cada vez que hago alt+shift+F se me cambian todas las comillas simples a dobles

2021-11-09 08:46 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/index.jsx
> +import { useState } from "react";
Es una configuración de visual, se puede cambiar

2021-11-09 08:46 UTC, JhonAires-Anima commented on frontend/src/pages/Home/index.jsx
>      <div className={classes.container}>
No comprendo a qué te referís, si son cosas distintas

2021-11-09 08:51 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/AllPots/index.jsx
> +              )}
Si te referís al .map lo único que tenes que hacer es mandarle por props la información al componente, y si es por una función externa también podes mandar un puntero a esa función por props

2021-11-09 09:19 UTC, Katherine-Damires commented on frontend/src/pages/Home/index.jsx
>      <div className={classes.container}>
En la rama ver ollas, un día en ánima le dijiste que lo separara y eso hice, en esa rama que utilizará la parte que tiene las tabs como componente, entonces el home no quedó tan cargado

2021-11-09 12:54 UTC, Katherine-Damires commented on frontend/src/components/ViewAllPots/AllPots/index.jsx
> +              )}
hay que entregar jhon, dejame seguir con otra cosa

2021-11-09 15:23 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/AllPots/index.jsx
> +              )}
?

2021-11-10 13:44 UTC, JhonAires-Anima requested changes

2021-11-10 13:44 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/ViewAllPots.module.scss
> +      color: #bd3131;
archivo de colores

2021-11-10 13:44 UTC, JhonAires-Anima commented on frontend/src/components/ViewAllPots/Cards/Cards.module.scss
> +  }
linea al final del archivo

2021-11-10 14:09 UTC, JhonAires-Anima approved these changes

2021-11-10 14:10 UTC, merged